import { defineArrayMember, defineField, defineType } from "sanity";
import { sanityLanguageIds } from "../../languages";
import { uniqueLanguageRule } from "./pages";

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Site settings",
  type: "document",
  groups: [
    { name: "identity", title: "Identity", default: true },
    { name: "header", title: "Header" },
    { name: "footer", title: "Footer" },
    { name: "integrations", title: "Editorial integrations" },
    { name: "messages", title: "Shared UI and forms" },
    { name: "seo", title: "Default SEO" },
    { name: "workflow", title: "Workflow" },
  ],
  fields: [
    defineField({
      name: "internalTitle",
      title: "Internal title",
      type: "string",
      group: "identity",
      initialValue: "Site settings",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "siteName",
      title: "Site name",
      type: "string",
      group: "identity",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "tagline",
      title: "Tagline",
      type: "string",
      group: "identity",
    }),
    defineField({
      name: "organizationDescription",
      title: "Organization description",
      type: "text",
      rows: 4,
      group: "identity",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "logo",
      title: "Primary logo",
      type: "contentImage",
      group: "identity",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "darkLogo",
      title: "Dark-background logo",
      type: "contentImage",
      group: "identity",
    }),
    defineField({
      name: "favicon",
      title: "Favicon",
      type: "image",
      group: "identity",
    }),
    defineField({
      name: "skipLinkLabel",
      title: "Skip-link label",
      type: "string",
      group: "header",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "announcementText",
      title: "Announcement text",
      type: "string",
      group: "header",
    }),
    defineField({
      name: "announcement",
      title: "Announcement action",
      type: "contentLink",
      group: "header",
    }),
    defineField({
      name: "primaryNavigation",
      title: "Primary navigation",
      type: "array",
      group: "header",
      of: [defineArrayMember({ type: "contentLink" })],
      validation: (rule) => rule.required().min(1).max(12),
    }),
    defineField({
      name: "solutionsNavigationLabel",
      title: "Solutions menu label",
      type: "string",
      group: "header",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "solutionsNavigation",
      title: "Solutions navigation",
      type: "array",
      group: "header",
      of: [defineArrayMember({ type: "contentLink" })],
      validation: (rule) => rule.required().min(1).max(20),
    }),
    defineField({
      name: "resourcesNavigationLabel",
      title: "Resources menu label",
      type: "string",
      group: "header",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "resourcesNavigation",
      title: "Resources navigation",
      type: "array",
      group: "header",
      of: [defineArrayMember({ type: "contentLink" })],
      validation: (rule) => rule.required().min(1).max(12),
    }),
    defineField({
      name: "headerPrimaryCta",
      title: "Primary header call to action",
      type: "callToAction",
      group: "header",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "headerSecondaryCta",
      title: "Secondary header call to action",
      type: "callToAction",
      group: "header",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "mobileMenuTitle",
      title: "Mobile-menu title",
      type: "string",
      group: "header",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "mobileMenuOpenLabel",
      title: "Open-menu label",
      type: "string",
      group: "header",
    }),
    defineField({
      name: "mobileMenuCloseLabel",
      title: "Close-menu label",
      type: "string",
      group: "header",
    }),
    defineField({
      name: "footerHeading",
      title: "Footer heading",
      type: "string",
      group: "footer",
    }),
    defineField({
      name: "footerDescription",
      title: "Footer description",
      type: "text",
      rows: 3,
      group: "footer",
    }),
    defineField({
      name: "footerCta",
      title: "Footer call to action",
      type: "callToAction",
      group: "footer",
    }),
    defineField({
      name: "quickLinksHeading",
      title: "Quick-links heading",
      type: "string",
      group: "footer",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "quickLinks",
      title: "Quick links",
      type: "array",
      group: "footer",
      of: [defineArrayMember({ type: "contentLink" })],
      validation: (rule) => rule.max(20),
    }),
    defineField({
      name: "solutionLinksHeading",
      title: "Solution-links heading",
      type: "string",
      group: "footer",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "solutionLinks",
      title: "Solution links",
      type: "array",
      group: "footer",
      of: [defineArrayMember({ type: "contentLink" })],
      validation: (rule) => rule.max(20),
    }),
    defineField({
      name: "linkedinCompanyId",
      title: "LinkedIn company ID",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "linkedinFollowCounter",
      title: "Show LinkedIn follower counter",
      type: "boolean",
      initialValue: false,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "socialLinksHeading",
      title: "Social-links heading",
      type: "string",
      group: "footer",
    }),
    defineField({
      name: "socialLinks",
      title: "Social links",
      type: "array",
      group: "footer",
      of: [defineArrayMember({ type: "contentLink" })],
      validation: (rule) => rule.max(12),
    }),
    defineField({
      name: "copyright",
      title: "Copyright text",
      type: "string",
      group: "footer",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "footerHashtag",
      title: "Footer hashtag",
      type: "string",
      group: "footer",
    }),
    defineField({
      name: "contactEmail",
      title: "Contact email",
      type: "string",
      group: "integrations",
      validation: (rule) => rule.email(),
    }),
    defineField({
      name: "careersEmail",
      title: "Careers email",
      type: "string",
      group: "integrations",
      validation: (rule) => rule.email(),
    }),
    defineField({
      name: "salesCareersEmail",
      title: "Sales careers email",
      type: "string",
      group: "integrations",
      validation: (rule) => rule.email(),
    }),
    defineField({
      name: "whatsappLink",
      title: "WhatsApp link",
      type: "url",
      group: "integrations",
      validation: (rule) => rule.uri({ scheme: ["https"] }),
    }),
    defineField({
      name: "calendlyUrl",
      title: "Calendly URL",
      type: "url",
      group: "integrations",
      validation: (rule) => rule.uri({ scheme: ["https"] }),
    }),
    defineField({
      name: "youtubeChannel",
      title: "YouTube channel",
      type: "url",
      group: "integrations",
      validation: (rule) => rule.uri({ scheme: ["https"] }),
    }),
    defineField({
      name: "sharedContactForm",
      title: "Contact form copy",
      type: "formCopy",
      group: "messages",
    }),
    defineField({
      name: "contactFormEmail",
      title: "Contact-form email",
      type: "formEmailTemplate",
      group: "messages",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "pocFormEmail",
      title: "POC-waitlist email",
      type: "formEmailTemplate",
      group: "messages",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "partnerFormEmail",
      title: "Partnership-form email",
      type: "formEmailTemplate",
      group: "messages",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "viewAllLabel",
      title: "View-all label",
      type: "string",
      group: "messages",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "loginPageTitle",
      title: "Login page title",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "dashboardPageTitle",
      title: "Dashboard page title",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "notFoundTitle",
      title: "Not-found title",
      type: "string",
      group: "messages",
    }),
    defineField({
      name: "notFoundDescription",
      title: "Not-found description",
      type: "text",
      rows: 3,
      group: "messages",
    }),
    defineField({
      name: "notFoundAction",
      title: "Not-found action",
      type: "callToAction",
      group: "messages",
    }),
    defineField({
      name: "goToTopLabel",
      title: "Go-to-top label",
      type: "string",
      group: "messages",
    }),
    defineField({
      name: "playVideoLabel",
      title: "Play-video label",
      type: "string",
      group: "messages",
    }),
    defineField({
      name: "closeDialogLabel",
      title: "Close-dialog label",
      type: "string",
      group: "messages",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "calendlyLoadingLabel",
      title: "Scheduling-widget loading label",
      type: "string",
      group: "messages",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "previousSlideLabel",
      title: "Previous-slide label",
      type: "string",
      group: "messages",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "nextSlideLabel",
      title: "Next-slide label",
      type: "string",
      group: "messages",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "llmsLinkTitle",
      title: "LLM index discovery-link title",
      type: "string",
      group: "messages",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "ogBadgeLabel",
      title: "Generated social image badge",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "websiteDisplayUrl",
      title: "Website display URL",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "twitterSiteHandle",
      title: "Twitter/X site handle",
      description: "Include the @ prefix.",
      type: "string",
      group: "seo",
    }),
    defineField({
      name: "twitterCreatorHandle",
      title: "Twitter/X creator handle",
      description: "Include the @ prefix.",
      type: "string",
      group: "seo",
    }),
    defineField({
      name: "contactPointType",
      title: "Organization contact-point type",
      type: "string",
      group: "seo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "defaultSeo",
      title: "Default SEO",
      type: "seo",
      group: "seo",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "language",
      title: "Language",
      type: "string",
      group: "workflow",
      readOnly: true,
      hidden: true,
      options: {
        list: sanityLanguageIds.map((id) => ({ title: id, value: id })),
      },
      validation: (rule) =>
        rule.required().custom(uniqueLanguageRule("siteSettings")),
    }),
    defineField({
      name: "translation",
      title: "Translation",
      type: "translationWorkflow",
      group: "workflow",
      validation: (rule) => rule.required(),
    }),
  ],
  preview: {
    select: { title: "internalTitle", language: "language" },
    prepare: ({ title, language }) => ({
      title: title || "Site settings",
      subtitle: language?.toUpperCase(),
    }),
  },
});
